services:
  mysql:
    image: mysql:5.7 # MySQL のバージョンを指定
    container_name: db-for-go
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_USER: ${ROOTUSER}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      TZ: "Asia/Tokyo"
    ports:
      - "4000:3306"
    volumes:
      - db-volume:/var/lib/mysql
      - ./createTable.sql:/docker-entrypoint-initdb.d/createTable.sql
      - ./insertData.sql:/docker-entrypoint-initdb.d/insertData.sql

volumes:
  db-volume:
